<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Pre Order'); ?>
<?php if ($_product->isSaleable()) : ?>
    <?php $jsOptions = json_encode(array(
        'product' => $_product->getId(),
        'mode' => Mage::getStoreConfig('agere_preOrder/settings/mode'),
        'fancybox' => array(
            'type' => "ajax",
            'href' => $this->getUrl('pre-order/index/getForm'),
        ),
    )); ?>
	<div class="add-to-cart">
		<button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" data-options='<?php echo $jsOptions ?>'>
			<span><span><i class="icon-cart"></i><?php echo $buttonTitle ?></span></span>
		</button>
        <?php echo $this->getChildHtml('', true, true) ?>
	</div>
<?php endif; ?>